(()=>{
  const SUPABASE_URL='https://zjwunducqyvueapqdeqx.supabase.co';
  const SUPABASE_KEY='sb_publishable_sOKL5gFe82ZsEemL_FbpfA_iQGen5Qn';
  const APP_URL='https://ultracker.online/';
  const CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
  let sb=null,user=null,syncTimer=null;
  const $=s=>document.querySelector(s);
  const history=()=>{try{return JSON.parse(localStorage.getItem('ul_history')||'[]')}catch{return[]}};
  const program=()=>{try{return JSON.parse(localStorage.getItem('ul_program')||'null')}catch{return null}};
  const profile=()=>{try{const p=JSON.parse(localStorage.getItem('ul_profile')||'null');if(p&&typeof p==='object')return p}catch{}const name=localStorage.getItem('ul_profile_name')||'';return name?{name}:{};};
  const toast=msg=>{const t=$('#toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}};
  const loadScript=()=>new Promise((resolve,reject)=>{if(window.supabase)return resolve();const s=document.createElement('script');s.src=CDN;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
  const style=()=>{};
  const passwordRecovery=()=>{let m=$('#passwordRecovery');if(m)return;const el=document.createElement('div');el.className='cloud-auth';el.id='passwordRecovery';el.innerHTML='<div class="cloud-box"><div style="font-size:12px;color:#39ffb6;font-weight:900;margin-bottom:8px">UL TRACKER • CLOUD</div><h2>Vaihda salasana</h2><div style="font-size:12px;color:#8e9aaa;margin-bottom:12px">Anna uusi salasana tilillesi.</div><input class="cloud-input" id="newPass" type="password" autocomplete="new-password" placeholder="Uusi salasana"><input class="cloud-input" id="newPass2" type="password" autocomplete="new-password" placeholder="Uusi salasana uudelleen"><div class="cloud-actions"><button class="btn primary" id="saveNewPass">Vaihda salasana</button></div><div class="cloud-status" id="passStatus"></div></div>';document.body.appendChild(el);$('#saveNewPass').onclick=async()=>{const a=$('#newPass').value,b=$('#newPass2').value;if(a.length<6)return $('#passStatus').textContent='Salasanan pitää olla vähintään 6 merkkiä.';if(a!==b)return $('#passStatus').textContent='Salasanat eivät täsmää.';const r=await sb.auth.updateUser({password:a});if(r.error)return $('#passStatus').textContent=r.error.message;el.remove();toast('Salasana vaihdettu ✓');await finish((await sb.auth.getUser()).data.user)};};
  const sync=async(force=false)=>{if(!sb||!user)return;clearTimeout(syncTimer);if(!force){syncTimer=setTimeout(()=>sync(true),1200);return}const h=history(),p=program(),profileData=profile();const {error}=await sb.from('user_data').upsert({user_id:user.id,history_json:h,program_json:p,profile_json:profileData,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)toast('Pilvitallennus epäonnistui');else toast('☁️ Tallennettu pilveen')};
  const finish=async u=>{if(!u)return;user=u;const {data,error}=await sb.from('user_data').select('history_json,program_json,profile_json,updated_at').eq('user_id',user.id).maybeSingle();if(error){toast('Pilvidatan luku epäonnistui');return}const local=history(),lp=program();if(data){if(Array.isArray(data.history_json)&&data.history_json.length){localStorage.setItem('ul_history',JSON.stringify(data.history_json));if(typeof window.renderHistory==='function')window.renderHistory();if(typeof window.renderProgress==='function')window.renderProgress();}if(data.program_json&&Array.isArray(data.program_json.days)){localStorage.setItem('ul_program',JSON.stringify(data.program_json));window.dispatchEvent(new CustomEvent('ul-cloud-program-loaded',{detail:data.program_json}));}if(data.profile_json&&typeof data.profile_json==='object'){localStorage.setItem('ul_profile',JSON.stringify(data.profile_json));if(typeof data.profile_json.name==='string'){localStorage.setItem('ul_profile_name',data.profile_json.name);}window.dispatchEvent(new CustomEvent('ul-profile-loaded',{detail:data.profile_json}));if(typeof window.renderWorkoutHome==='function')window.renderWorkoutHome();}}if(!data||(!Array.isArray(data.history_json)||!data.history_json.length)&&local.length||(!data?.program_json&&lp)||(!data?.profile_json&&Object.keys(profile()).length)){await sync(true)}toast('☁️ Pilvitallennus käytössä')};
  const boot=async()=>{style();try{await loadScript();sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);sb.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){passwordRecovery();return}if(event==='SIGNED_IN'&&session&&!user)await finish(session.user)});const r=await sb.auth.getUser();if(r.data.user)await finish(r.data.user);else location.replace('./index.html');document.addEventListener('click',e=>{if(e.target.closest('#saveBtn'))setTimeout(()=>sync(true),900)},true);window.addEventListener('storage',()=>sync(false));window.addEventListener('ul-program-changed',()=>sync(false));window.addEventListener('ul-profile-changed',()=>sync(false));}catch(e){console.error(e);toast('Pilvipalvelun käynnistys epäonnistui')}};
  setTimeout(boot,0);
})();